version: "3"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: speedrun_lisk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
