/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui"), require("@tailwindcss/typography")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#4070F4",
          "primary-content": "#ffffff",
          secondary: "#E8EFFF",
          "secondary-content": "#1A365D",
          accent: "#7B9BFF",
          "accent-content": "#1A365D",
          neutral: "#2D3748",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#F7FAFC",
          "base-300": "#E2E8F0",
          "base-content": "#1A202C",
          info: "#3182CE",
          success: "#38A169",
          warning: "#D69E2E",
          error: "#E53E3E",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#7B9BFF",
          "primary-content": "#1A202C",
          secondary: "#2D3748",
          "secondary-content": "#F7FAFC",
          accent: "#4070F4",
          "accent-content": "#ffffff",
          neutral: "#F7FAFC",
          "neutral-content": "#1A202C",
          "base-100": "#1A202C",
          "base-200": "#2D3748",
          "base-300": "#4A5568",
          "base-content": "#F7FAFC",
          info: "#63B3ED",
          success: "#68D391",
          warning: "#F6E05E",
          error: "#FC8181",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      colors: {
        violet: "#606CCF",
        "violet-light": "#D9DDFF",
      },
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
    },
  },
};
